**Setup**
```{r}
library(kernlab)
#library(car)
library(ggplot2)
library(corrgram)
library(vcd)
library(rpart)
library(randomForest)
library(e1071)
library(nnet)
library(MASS)
library(bootstrap)
library(DAAG)
```

### 2.1.1 Import Dataset
```{r}
data(ticdata)
#raw <- read.csv('../ticdata2000.csv')
data <- ticdata[1:5822,]
```

#### Association Plot (Original Categ. Vars.)
_Works with categorical variables_
_Paused for the time being to increase speed_
```{r, fig.width=4, fig.height=4}
for(i in 1:64){
  t <- table(data[,c(i, 86)])
  assoc(t, shade=T)
}
```

#### Bar Plots (Original Categ. Vars.)
```{r, fig.width=4, fig.height=3}
for(i in 1:64){
  p <- ggplot(data, aes(x=data[,i], fill=CARAVAN)) +
    geom_bar() +
    labs(x=names(data)[i])
  print(p)
}
```

#### Box/whisker Plot (Original Num. Vars.)
```{r, fig.width=4, fig.height=3}
for(i in 65:85){
  formula.string <- paste(names(data)[i],'CARAVAN',sep='~')
  f <- as.formula(formula.string)
  boxplot(f, data, main=names(data)[i])
}
```

#### Association Plot (Converted Num. Vars.)
_Works with categorical variables_
_Paused for the time being to increase speed_
```{r, fig.width=4, fig.height=4}
dc <- as.data.frame(lapply(data, as.factor)) # transform all to categorical

for(i in 65:85){
  t <- table(dc[,c(i, 86)])
  assoc(t, shade=T)
}
```

#### Bar Plots (Converted Num. Vars.)
```{r, fig.width=4, fig.height=3}
dc <- as.data.frame(lapply(data, as.factor)) # transform all to categorical

for(i in 65:85){
  p <- ggplot(dc, aes(x=dc[,i], fill=CARAVAN)) +
    geom_bar() +
    labs(x=names(dc)[i])
  print(p)
}
```

